zsh: improve nnn plugin
Do not `cd` to the directory if the target directory is `$PWD`

diff --git a/zsh/.config/zsh/.zsh-plugins/nnn-quitcd/n b/zsh/.config/zsh/.zsh-plugins/nnn-quitcd/n
--- a/zsh/.config/zsh/.zsh-plugins/nnn-quitcd/n
+++ b/zsh/.config/zsh/.zsh-plugins/nnn-quitcd/n
@@ -1,3 +1,5 @@
+emulate -L zsh
+
 # Block nesting of nnn in subshells
 [ "${NNNLVL:-0}" -eq 0 ] || {
     echo "nnn is already running"
@@ -22,6 +24,11 @@ export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"
 command nnn "$@"
 
 [ ! -f "$NNN_TMPFILE" ] || {
-    . "$NNN_TMPFILE"
-    rm -f "$NNN_TMPFILE" > /dev/null
+    if [[ "$(command cat $NNN_TMPFILE)" =~ "cd '(.*)'" ]]; then
+        target_dir="${match[1]}"
+        [[ "$PWD" = "$target_dir" ]] || cd "$target_dir"
+        rm -f "$NNN_TMPFILE" > /dev/null
+    else
+        printf '%s\n' "regex match failed" >&2
+    fi
 }
